### ISSUE TITLE
Abstraction layer to add metrics in Go hooks

### ISSUE THREAD

**Issue by nabokihms** [flant/addon-operator#211]
**Is your feature request related to a problem? Please describe.**
The problem is that as for now, the only way to return a metric sample from a go hook is to append an internal structure to the slice of metric operations like
```go
*input.Metrics = append(*input.Metrics, operation.MetricOperation{
  Name:   "my_metric",
  Action: "set",
  Value:   pointer.Float64Ptr(1),
})
```
It is not convenient in many ways.

**Describe the solution you'd like to see**
It seems reasonable to describe a thin level of abstraction around metrics operations.
Like this:
```go
input.Metrics.ExpireGroup("my_group")

input.Metrics.WithName("my_metric_1").Set(1)
input.Metrics.WithName("my_metric_2").Add(1)
input.Metrics.WithName("my_metric_2").WithGroup("my_group").Observe(1)
```

**Describe alternatives you've considered**
Leave it as is.

**Additional context**

**Comment by diafour** [comment]
Metric collector is implemented, close this.
