### ISSUE TITLE
Add go module

### ISSUE THREAD

**Issue by mcristina422** [flant/addon-operator#25]
Use go modules instead of go get 

Builds: 
https://github.com/flant/addon-operator/blob/22bd314ffdfe469c9cfc3238427920b4ea5309e6/Dockerfile#L4

https://github.com/flant/addon-operator/blob/22bd314ffdfe469c9cfc3238427920b4ea5309e6/Dockerfile-alpine3.9#L4

https://github.com/golang/go/wiki/Modules

**Comment by diafour** [comment]
Hello! Is this a blocking issue for your use case right now or a just a good advice? There is a plan to migrate shell-operator and addon-operator to modules in the long run.

**Comment by zuzzas** [comment]
@diafour 
We should close this issue since it's fixed.
https://github.com/flant/addon-operator/pull/29

**Comment by diafour** [comment]
Fixed. @mcristina422 modules are introduced in PR #29.
