### ISSUE TITLE
Prioritize global hooks above modules

### ISSUE THREAD

**Issue by keir86** [flant/addon-operator#30]
Hi there.
Thank you for the cool stuff!
Let me describe the case to make this proposal clear.

I have a global hook `self-update.sh` (with schedule task)  which every N minutes checks a new addon-operator image and pull it to a cluster. This move brings new modules / patches / etc to a cluster.

Then, I have made some broken module `my-module-X`, which can not be deployed due to some reasons (just personal mistake, env troubles, etc). And it has stucked in the task queue, trying to be released every 5 seconds.
After I have found an error into the module and have fix it, I pull the new image with addon-operator. So, it seems pretty easy: currently working addon-operator pod should find the new image in a few minutes and redeploy it but it`s not possible, because the tasks queue stucked in the next state:
```
Queue length 296

TASK_MODULE_RUN 'my-module-X' failed 579 times. 
# other modules #
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
TASK_GLOBAL_HOOK_RUN 'self-update.sh'
...
```

The solution here is to redeploy addon-operator pod in all clusters. But is brokes all the automation stuff.

That would be nice if global hooks (or maybe only schedule tasks) come at the top of the queue. It will make self-repairing based on schedule/event possible.

Thank you.

**Comment by diafour** [comment]
Hello. I can recommend a workaround for blocked hook: use a sidecar container with shell-operator and self-update.sh.

P.S. We have the same pull model with out clusters. Our solution for updates is a golang code that checks for image digest in status section of pod and fetch metadata from registry and restarts a Deployment if they are not matched. There is a plan to release it in a form of sidecar.

**Comment by keir86** [comment]
Yeah. Like a workaround solution I also made a sidecar with crond and script. Sure it works but addon-operator has all required tools to be self-sufficient. And it looks quite reasonable to execute global hooks in a separate goroutine.At the same time, container with config reloader looks more k8s way. It depends...

Anyway, it`s up too you, I didn`t investigate the code well, maybe this change could break something.

Thank you for the answer. I think this issue could be closed if you regard this kind of changes unnecessary or dangerous.

**Comment by diafour** [comment]
Global hooks are considered to be a part of addons, that is why they are queued to the same working queue with modules. For now, one working queue — one addon-operator instance. And there is no plans to implement multiple working queues. So «Prioritize global hooks above modules» is a no-go for now.

May be there is a good idea to implement a special kind of hooks with separate working queue. Something like maintenance hooks or service hooks.
