### ISSUE TITLE
Allow disabling of module having errors (during it's installation or in hooks)

### ISSUE THREAD

**Issue by distol** [flant/addon-operator#43]
The current implementation has possible deadlock: if the module has errors, either in the helm templates or in hooks, the tasks are stuck in the queue and disabling the module in ConfigMap don't help, because of module tasks are not removed from the queue.

Proposed change: When the module becomes disabled (in ConfigMap, or by any other means) the following should happen (in the following order):
1. All informers should be stopped and all crontab bindings should be disabled, so no new tasks (possibly containing errors) will be added to the queue.
2. All existing module tasks should be removed from the queue.
3. Tasks associated with module disabling should be added (helm uninstall, and afterDeleteHelm hooks)

**Comment by diafour** [comment]
Error in enabled script can also cause this situation. #16
