### ISSUE TITLE
Eliminate hard code regex for module name

### ISSUE THREAD

**Issue by diafour** [flant/addon-operator#7]
```
bad module directory names, must match regex '^[0-9][0-9][0-9]-(.*)$': /addons/modules/sysctl-tuner
```

**Comment by distol** [comment]
Module ordering is an important part of addon-operator LIFECYCLE. And the ability to change module order not changing its name extremely important. But yes, using the part of the directory name for this purpose is far from the best way. Closed in favor of #39.
